### ISSUE TITLE
Can´t mine stone using a pickaxe

### ISSUE THREAD

**Issue by AlexanderDotH** [ReviversMC/modern-glass-doors#18]
I know it sounds strange. I made a modpack for my girlfriend and me and I faced a weird issue where I can`t mine any stone related blocks while this mod was installed. We played on a server environment. If you need more details, please tell me

**Comment by thefirethirteen** [comment]
Could you share what mods you are using along with their exact versions? Also the Minecraft version and Modern Glass Doors version? Thanks!

**Comment by AlexanderDotH** [comment]
Of course! We use those mods:

  [✔] abverticaledition-1.0.3b-fabric-mc1.20
  [✔] antighost-1.19.3-fabric0.68.1-1.1.5
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] architectury-9.0.8-fabric
  [✔] balm-fabric-1.20-7.0.3
  [✔] bclib-3.0.7
  [✔] betterarcheology-1.0.1
  [✔] betterbeds-1.3.0-1.19.3
  [✔] better-end-4.0.3
  [✔] BetterF3-7.0.0-Fabric-1.20-pre6
  [✔] bettermounthud-1.2.2
  [✔] better-nether-9.0.5
  [✔] blockus-2.7.1+1.20
  [✔] blur-3.1.0
  [✔] borderless-mining-1.1.7+1.19.4
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.10.91
  [✔] capes-1.5.2+1.20-fabric
  [✔] chat_heads-0.10.16-fabric-1.20
  [✔] CITResewn-1.1.3+1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] clutter-1.20.1-0.3.6
  [✔] collective-1.20.1-6.59
  [✔] continuity-3.0.0-beta.2+1.20
  [✔] cookingforblockheads-fabric-1.20-16.0.0
  [✔] culinaryconstruct-fabric-5.2.0+1.20.1
  [✔] Debugify-1.20.1+1.1
  [✔] doubledoors-1.20.1-4.5
  [✔] dungeons-and-taverns-v2.1.3
  [✔] dynamic-fps-2.3.0
  [✔] e4mc-3.2.0+1.19.4-fabric
  [✔] eating-animation-1.9.4+1.20
  [✔] emi-1.0.4+1.20.1+fabric
  [✔] entity_model_features_fabric_1.20-0.2.10
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] fabric-api-0.83.1+1.20.1
  [✔] fabric-language-kotlin-1.9.5+kotlin.1.8.22
  [✔] fabricskyboxes-0.7.1+mc1.20
  [✔] fabrishot-1.9.2
  [✔] fadeless-1.0.1
  [✔] fallingleaves-1.15.1+1.20.1
  [✔] ferritecore-6.0.0-fabric
  [✘] firstperson-fabric-2.2.3-mc1.20.jar (disabled)
  [✔] forgottengraves-1.20.1-3.1.0
  [✔] fsb-interop-1.3.2+mc1.20-build.36
  [✔] fullbrightnesstoggle-1.20.1-3.0
  [✔] geckolib-fabric-1.20-4.2
  [✔] geophilic-v2.0.0-mc1.20u1.20.1
  [✔] handcrafted-fabric-1.20-2.3.2
  [✔] holdthatchunk-2.0.1+1.19
  [✔] icarus-1.16
  [✔] idwtialsimmoedm-0.2.0+1.20
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] immersive-portals-3.1.0-mc1.20.1-fabric
  [✔] indium-1.0.18+mc1.20
  [✔] interactic-0.2.0+1.20
  [✔] invhud.fabric.1.20-3.4.13
  [✔] InvMove-1.20-0.8.4-Fabric
  [✔] iris-mc1.20-1.6.4
  [✔] IronChests-2.0.0
  [✔] jei-1.20.1-fabric-15.0.0.17
  [✔] journeymap-1.20.1-5.9.9-fabric
  [✔] language-reload-1.5.7+1.20
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] main-menu-credits-1.1.2
  [✔] mavapi-1.1.0-mc1.20
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] midnightcontrols-1.8.2+1.20
  [✔] mixintrace-1.1.1+1.17
  [✔] modelfix-1.10-fabric
  [✔] modmenu-7.0.1
  [✔] moonlight-1.20-2.5.8-fabric
  [✔] more-axolotl-2.0.0-1.20
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moreculling-1.20-0.18.0
  [✔] movingelevators-1.4.3-fabric-mc1.20
  [✔] name-visibility-1.1.0+1.19.4-1.20
  [✔] notenoughanimations-fabric-1.6.4-mc1.20
  [✔] Nyctophobia_1.9_(FABRIC)_for_1.20+
  [✔] optigui-2.1.2
  [✔] owo-lib-0.11.0+1.20
  [✔] pack_it_up-0.3.0+1.20.1
  [✔] peek-1.20.1-1.0.5
  [✔] Philips-Ruins1.20.1-1.0[Fabric]
  [✔] physics-mod-3.0.5-mc-1.20-fabric
  [✔] plushie-mod-1.2.1
  [✔] profundis-1.5.0
  [✔] puzzle-1.5.1+1.20
  [✔] reeses_sodium_options-1.5.1+mc1.20-build.74
  [✔] resourcefullib-fabric-1.20.1-2.1.0
  [✔] seamless-1.3.0-fabric-1.19.2
  [✔] sfcr-1.7.3-1.20
  [✔] showdurability-1.1.0+1.20.1
  [✔] simple-hud-enhanced+1.20-1.20.1-v2.0.0
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] soundphysics-fabric-1.20.1-1.1.1
  [✔] supermartijn642configlib-1.1.6-fabric-mc1.20
  [✔] supermartijn642corelib-1.1.9-fabric-mc1.20
  [✔] tectonic-mod-mc1.20-v2
  [✔] TerraBlender-fabric-1.20.1-3.0.0.164
  [✔] trashcans-1.0.17-fabric-mc1.20
  [✔] traverse-7.0.6
  [✔] trinkets-3.7.0
  [✔] vanilla-refresh-1.4.16b
  [✔] VarietyAPI-Fabric-1.0
  [✔] villagernames-1.20.1-5.2
  [✔] waveycapes-fabric-1.4.0-mc1.20
  [✔] yet-another-config-lib-fabric-3.0.1+1.20
  [✔] yosbr-0.1.2
  [✔] Zoomify-2.10.0

**Comment by skwhiteley** [comment]
I am having the same issue. Removing the mod allows me to mine stone with a pickaxe on reset. The doors also disappear when you try to place them. I am using fabric and the latest version. I can post an exact mod list if it would be helpful, but I tried running it individually in a solo user world, and the same issue occurs. Please update if this gets fixed, my boyfriend and I really like this mod!

**Comment by thefirethirteen** [comment]
I can't seem to replicate the bug... could you provide me with the exact versions of Minecraft, this mod, fabric-api and fabric loader?

**Comment by AlexanderDotH** [comment]
It's happening in multiplayer. I use the latest recommend fabric version

**Comment by AlexanderDotH** [comment]
Yeah I removed the mod. I'm in the newest 1.20

**Comment by vico93** [comment]
I think this is somewhat related to #19 ...

I had this issue (but weirdly only on dedicated server) and went to Fabric's Discord and where @AkashiiKun told me to use [Load my 🤬 Tags](https://github.com/Dragon-Seeker/LoadMyFuckingTags)([MR](https://modrinth.com/mod/lmft)) because they thought some mod was breaking vanilla and other mods tags. With that installed, i was able to play on my test server, although LMFT keeps telling me when connecting that some mod was breaking tags and it was fixing it.

Since i play mostly singleplayer and don't have logs enabled on the launcher i don't paid attention to what mod was doing that, but after trying to setup again a test server i noticed the real deal. Not only LMFT was spamming the console with errors related to this mod items but also there was a lot of JSON errors from this mod loot tables.

I really thing the datapack part of this mod is really broken and somewhat bringing down (almost) the whole vanilla tag system,  and LMFT just try to bring the whole thing up again. But since you guys don't use that the tags are kept down and even basic things like stone breaking stays unusable.

**Comment by NebelNidas** [comment]
Thanks for the additional details. The weird thing is, all of our tags are generated by Fabric's first-party Datagen API, so I'm not sure how fraudulent entries could end up there. Does this issue happen with 1.19.4 as well?

**Comment by NebelNidas** [comment]
Should be fixed now! Can you confirm if the latest build works for you? https://github.com/ReviversMC/modern-glass-doors/actions/runs/5436461761

**Comment by vico93** [comment]
> Should be fixed now! Can you confirm if the latest build works for you? https://github.com/ReviversMC/modern-glass-doors/actions/runs/5436461761

Will try on my test server right now!

**Comment by vico93** [comment]
No lines on the log! [Here](https://gist.github.com/vico93/1e12f896cfe77770e22a9bab3dc50d22)

**Comment by NebelNidas** [comment]
Perfect! If there are no issues, we're going to publish a new release containing this fix sometime tomorrow 👍
